version: '3.8'

services:
  # db:
  #   image: mariadb:latest
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   volumes:
  #     - ./data:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  #
  #   networks:
  #     - solufit
  #
  #   env_file:
  #     - .env


  api:
    build:
      context: .
      dockerfile: ./docker/api/dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      DEBUG: "True"

    networks:
      - solufit
    
    env_file:
      - .env
  
  web:
    build:
      context: .
      dockerfile: ./docker/front/dockerfile
    restart: always
    ports:
      - 8080:5173
    environment:
      VITE_API_ENDPOINT: "http://api:5000/v1/ai_web_search"

    networks:
      - solufit

    env_file:
      - .env

networks:
  solufit:
    external: true
